<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevMatch.Domain\DevMatch.Domain.csproj" />
    <ProjectReference Include="..\DevMatch.SharedKernel\DevMatch.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\" />
    <Folder Include="Features\Bookmarks\Commands\" />
    <Folder Include="Features\Bookmarks\DTO\" />
    <Folder Include="Features\Bookmarks\Handlers\" />
    <Folder Include="Features\Bookmarks\Query\" />
    <Folder Include="Features\Bookmarks\Validators\" />
    <Folder Include="Features\Issues\DTO\" />
    <Folder Include="Features\Issues\Query\" />
    <Folder Include="Features\Recommendations\Commands\" />
    <Folder Include="Features\Recommendations\DTO\" />
    <Folder Include="Features\Recommendations\Handlers\" />
    <Folder Include="Features\Recommendations\Query\" />
    <Folder Include="Features\Recommendations\Validators\" />
    <Folder Include="Features\Repositories\Commands\" />
    <Folder Include="Features\Repositories\DTO\" />
    <Folder Include="Messaging\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

</Project>
